### ISSUE TITLE
Install build for production (eg. not in devenv)

### ISSUE THREAD

**Issue by alex-vyverman** [centricular/webrtcsink#103]
Hi,

Props to this great project!
I've successfully build everything using Meson, and it works as intended in devenv.

What I can't seem to find is info on how to now install this build systemwide for production use? 
I'm using Ubuntu 22.04 if that is in any way relevant.

Many thanks!
Alex

**Comment by joaoantoniocardoso** [comment]
WebRTCSink (the plugin) is compiled into a single library file, so I should work if you just copy this file to your system's GStreamer directory.

Note that while just copying it to your own system is probably fine, MIT license allows anyone to redistribute it, but a copy of the license supposedly must be provided within the licensed material [[1](https://choosealicense.com/licenses/mit/)], probably copying it to `/usr/share/doc/webrtcsink/copyright` (Ubuntu/Debian based) or `/usr/share/licenses/webrtcsink/.` (Arch based) .

**Comment by MathieuDuponchelle** [comment]
What version of GStreamer ships with ubuntu 22.04?

**Comment by joaoantoniocardoso** [comment]
> ubuntu 22.04

[1.20.1-1](https://packages.ubuntu.com/jammy/libgstreamer1.0-0)

**Comment by MathieuDuponchelle** [comment]
Thanks @joaoantoniocardoso :) latest `webrtcsink` should run against that, if you explicitly select the homegrown congestion-control algorithm through the property @alex-vyverman . Closing as I think this was answered :)

**Comment by MathieuDuponchelle** [comment]
> Many thanks for the answers. I checked, and seem to have 1.20.3 installed trough apt. So webrtcsink should be able to run against this? I'll test again, but seem to remember running into trouble. I've never explicitly selected the homegrown congestion-control algorithm, so I'll give that a try!

Usage of the gcc algorithm depends on a webrtcbin signal that was only merged post 1.20, it is only a runtime requirement however, so selecting homegrown should be a valid workaround. I am not aware of other issues, but perhaps there are, I'll let others chime in if they know about something else :)
