### ISSUE TITLE
Remote desktop with navigation using ximagesrc

### ISSUE THREAD

**Issue by blackccpie** [centricular/webrtcsink#105]
Hello,

Is it possible to achieve some sort of web based remote desktop out of the box, using `webrtcsink` and `ximagesrc`?
In short, I would like to reproduce your navigation example, but using xwindow capture. The fact is `ximagesrc` does not implement the `GstNavigation` interface, so I was wondering if it was possible to achieve it in another way.

Thanks for your help,

Albert

**Comment by MathieuDuponchelle** [comment]
You could intercept the navigation events yourself in an application, and forward them manually? Ideally though you would implement support in whatever element you're targeting and contribute it upstream :) Closing as there are no activatable items here.
