### ISSUE TITLE
Relicense to MPL in order to harmonize with gst-plugins-rs prior to inclusion

### ISSUE THREAD

**Issue by MathieuDuponchelle** [centricular/webrtcsink#107]
Hey everybody,

We are eventually going to upstream this element in `gst-plugins-rs`, and for the sake of harmonization it would be nice to first of all relicense the plugin from the MIT license to the Mozilla Public License Version 2.0.

Please let me know if you're OK with this!

- [x] @Hejsil 
- [x] @septatrix 
- [x] @praveenperera 
- [x] @compiaffe 
- [x] @sdroege 
- [x] @thiblahute 
- [x] @vivienne-w 
- [x] @mfadhlika 
- [x] @machenmusik 
- [x] @massis08
- [x] @gondaruk 
- [x] @MathieuDuponchelle

**Comment by Hejsil** [comment]
:+1:

**Comment by septatrix** [comment]
Yes sure :D

**Comment by gondaruk** [comment]
I'm all for it 👍

**Comment by MathieuDuponchelle** [comment]
> (You should probably specify Mozilla Public License 2 though...)

Indeed, done :)

**Comment by praveenperera** [comment]
All good

**Comment by thiblahute** [comment]
All good.

**Comment by massis08** [comment]
All good!

**Comment by machenmusik** [comment]
Some confusion on my part, as I just looked at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs#license and it seems as though MIT is one of the four options; do we need to change?

If so (e.g. for whatever reason we don't like MIT anymore), is there a specific reason to choose MPL2 vs. Apache2 for example?

**Comment by tp-m** [comment]
[This gst-plugins-rs ticket](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/168) explains some of the rationale.

**Comment by septatrix** [comment]
> Some confusion on my part, as I just looked at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs#license and it seems as though MIT is one of the four options; do we need to change?


To my knowledge now, but the README also states: "For new plugins the MPL-2 license is preferred." and Mathieu also stated this is "...for the sake of harmonization...". So yeah currently there is a mix of four licenses used but it seems like they try to not keep all new contributions under MPL2.

> If so (e.g. for whatever reason we don't like MIT anymore), is there a specific reason to choose MPL2 vs. Apache2 for example?

First and foremost that this what the projects prefers for new plugins. I was also a bit confused by this but you can investigate the history of the repo a bit to get a clearer understanding. Previously many plugins in there were under LGPL-2.1-or-later which has problems in the context of statical linking https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/168. Some of the remaining plugins are published under MIT+Apache2 which is popular in the Rust community, not sure why that is not chosen but it would require a relicensing anyhow and MPL2 is to my understanding basically equivalent to the dual-licensing approach.

**Comment by machenmusik** [comment]
Thanks @septatrix for the detailed response.  I have no issues with MIT and/or Apache2 either, so was wondering why gst-plugins-rs doesn't seem to like that (and by implication, whether we agree).

**Comment by tp-m** [comment]
Users who have an issue with LGPL-2.1 will likely not be using anything built on top of GStreamer + GLib anyway, will they? :)

**Comment by machenmusik** [comment]
(They may have made their peace with certain portions they use now... but that may not extend to all new plugins...)

**Comment by mfadhlika** [comment]
All good

**Comment by sdroege** [comment]
> they try to not keep all new contributions under MPL2

All new plugins are MPL unless there's a really good reason why that's not possible and the plugin should be included nonetheless.

Back then I only bothered relicensing the LGPL 2.1 plugins (as the LGPL causes the most headaches in combination with Rust, see issue) so there are still MIT/Apache-licensed plugins available. Technically those MIT-licensed plugins (as well as webrtcsink) could also be relicensed to the MPL2 without any explicit agreement from the contributors as the MIT license explicitly allows sublicensing. If you search a bit, this is very common (mostly towards a commercial license or LGPL/GPL).

If there was any contribution to any of those MIT-licensed plugins where the contributor would prefer their changes to be published under the terms of the MPL2 then that's what would happen.

> MPL2 is to my understanding basically equivalent to the dual-licensing approach

The MPL is a weak copyleft license (basically requiring changes to the code to be published) while both MIT and Apache2 are not. That's why it is preferred for gst-plugins-rs as it is more in line with the "copyleft culture" of the GStreamer project, but doesn't have the technical problems of the LGPL.

**Comment by MathieuDuponchelle** [comment]
Thanks for the precisions folks, to be perfectly clear I am not a lawyer and my point here is solely to facilitate future upstreaming of this plugin, there's nothing I don't like about the MIT license or prefer about the MPL-2 license personally, but I defer to @sdroege as knowing best on this subject.

Let me know if you're OK now that your questions have (hopefully) been answered @machenmusik :)

**Comment by compiaffe** [comment]
Fine by me @MathieuDuponchelle 
That also goes for any contributions here done by Aivero AS (cc @Hejsil )

**Comment by machenmusik** [comment]
> Let me know if you're OK now that your questions have (hopefully) been answered @machenmusik :)

Thanks, reasoning is clear.  Just checking to make sure the company I know has interest will still be able to use as MPL2 ;-)

Is there a hard deadline by which we need to confirm definitely?

**Comment by MathieuDuponchelle** [comment]
@machenmusik for what it's worth we *are* going to make the switch at this point, if everyone had disagreed with the re-licensing then re-implementing all the patches would have been a tall order, but if you're the last person holding out I reckon I could manage to re-implement whatever would go missing :stuck_out_tongue:

This makes a hard deadline a bit pointless, but I guess I'd like to get this out of the way by next week. Note that I don't plan to start the upstreaming proper myself as I have other cats to skin right now, and others have (quite foolishly) volunteered themselves for the task :)

**Comment by machenmusik** [comment]
I did gather that - I am not trying to be obstructionist, to be clear, just trying to actually complete the diligence behind the yes if possible.  I expect to be checking the box tomorrow or early next week :-)

**Comment by MathieuDuponchelle** [comment]
cool :)

**Comment by MathieuDuponchelle** [comment]
Let's go, thanks everyone!
