### ISSUE TITLE
Fatal runtime error: failed to initiate panic, error 5. Aborted (core dumped) when closing the web

### ISSUE THREAD

**Issue by NanNguyen01** [centricular/webrtcsink#110]
Hi, 
I tried the latest main version of the code using the provided example run instructions. When I opened a browser's tab, I clicked on stream's peer-id about one or more times, then close the browser's tab, it would occasionally produce the following runtime error.
![image](https://user-images.githubusercontent.com/101386916/194988923-4de4c1fe-695a-4799-9bd7-32e0abc4130f.png)

**Comment by MathieuDuponchelle** [comment]
cc @thiblahute :)
