### ISSUE TITLE
Memory does not get fully deallocated when close sessions

### ISSUE THREAD

**Issue by anhquan1012** [centricular/webrtcsink#113]
I use the main branch.
Below are my steps to produce the issue:
1. Run the demo instruction in the readme.
2. Add one stream to the pipeline.
3. In the demo tab, click to open some connections (the memory will increase with every newly added connection).
4. Close the tab and watch the memory performance (the memory will not get freed entirely).

Can you check it? Thank you.

**Comment by MathieuDuponchelle** [comment]
@anhquan1012 I don't know what you mean by "add one stream to the pipeline", please be more specific on that point.

I can reproduce the issue anyway I think, CPU usage goes back down to its original level but memory usage does not, interesting :)

**Comment by anhquan1012** [comment]
It just means I add a stream by webrtcsink cli:
```
gst-launch-1.0 webrtcsink name=ws videotestsrc ! ws. audiotestsrc ! ws.
```

**Comment by MathieuDuponchelle** [comment]
I see thanks

**Comment by MathieuDuponchelle** [comment]
@anhquan1012 how are you observing the increasing memory usage? What I was using was the `RES` figure provided by `htop`, but I think what I first assumed were leaks is actually only my system allocator suffering from memory fragmentation. Looking at the memory profile with `heaptrack` actually shows nominal behavior, here's an example where I added 4 consumers, removed them, then added 4 new consumers:

![Screenshot from 2022-10-14 15-32-31](https://user-images.githubusercontent.com/1278273/195949053-4c6c1d4b-8176-4836-9c8d-c8f232496932.png)

I also sampled the `RES` figure in `htop` many times, each of the points in the graph below corresponds to the number of consumers going back and forth between 48 and 0:

![Figure_1](https://user-images.githubusercontent.com/1278273/195949169-dd1c3368-9d62-4659-b1ca-7cd48957c1f8.png)

As you can see, this comforts my understanding that the memory allocator is simply not avoiding fragmentation very well, as the total RES figure tends to progress towards a maximum at a decreasing pace, which can't be explained by leaks in the program, those should instead scale linearly.

I did run under valgrind and fixed a tiny leak in GStreamer however: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3188>, but that is unrelated in terms of scale :)

**Comment by anhquan1012** [comment]
Thanks for your analysis, I also used htop for observing.
Do you think it is a problem we can fix? And are you trying to fix it?

**Comment by MathieuDuponchelle** [comment]
Hey @anhquan1012 , if my analysis is correct, this is not a problem, at least not one you could fix at that level of the software stack, if you want to mitigate the effects of memory fragmentation you will need to use a custom, more efficient memory allocator. I will close this now, please reopen if you have evidence that webrtcsink actually leaks memory :)
