### ISSUE TITLE
Using with stable versions of GStreamer

### ISSUE THREAD

**Issue by piranna** [centricular/webrtcsink#12]
Current stable branch of GStreamer is 1.18.x. Is there any reason to need to use development 1.19.x branch? There are no packages published for it in Ubuntu or other distros since it's only an internal unstable in-development release, not ready for production... How can we proceed?

**Comment by MathieuDuponchelle** [comment]
Hey, you'll simply have to wait for 1.20 to be released and packaged, or run against git main, I had to make quite a few patches to various GStreamer components to make this element work as intended, in particular with respect to congestion control.
