### ISSUE TITLE
repo in guide not found

### ISSUE THREAD

**Issue by shu777** [centricular/webrtcsink#15]
git clone https://gitlab.freedesktop.org/meh/gstreamer/-/tree/webrtcsink
Cloning into 'webrtcsink'...
fatal: repository 'https://gitlab.freedesktop.org/meh/gstreamer/-/tree/webrtcsink/' not found

**Comment by MathieuDuponchelle** [comment]
Oops, not sure what happened there. Care to make a PR ? :)
