### ISSUE TITLE
Reduce latency between appsrc and WebRTC stream from websink?

### ISSUE THREAD

**Issue by fechan** [centricular/webrtcsink#20]
I'm new to Gstreamer in general and I've been scratching my head over this. Sorry if noob question, and thanks in advance.

## Question
Are there ways to reduce the latency between my appsrc and the appsrc being displayed on a browser that I could be doing when using webrtcsink?

## Background
I'm using GLFW to help me control OpenGL, and I'm able to get frames from OpenGL into webrtcsink. My appsrc gets frames from OpenGL with `glReadPixels` and sends them down the pipeline to webrtcsink, and you can see a WebRTC stream on the browser. My pipeline string looks like this:

```
appsrc name=appsrc ! video/x-raw,format=RGB,framerate=60/1,pixel-aspect-ratio=1/1,width=1920,height=1080 ! webrtcsink
```

When I press a button on the GLFW window, a spinning triangle that normally spins clockwise will spin counterclockwise. This also happens on the WebRTC stream on the browser, but there's up to a 2 second delay between it happening in the GLFW window and the stream when I'm using my lower spec computer (Linux/Intel 15-6200U/Intel HD Graphics 520/8gb RAM). On my good computer (Intel i7/Nvidia 1050ti), the latency is negligible.

### What works
- Throttling the rate at which appsrc receives buffers from OpenGL. When appsrc needs data, I set it to only push a new buffer every N milliseconds. The higher I set N, the better the latency gets, but the worse the FPS gets. I suspect webrtcsink being swamped with a lot of buffers to process is increasing latency.
- Using a different `video-caps` on webrtcsink. I've tried vp8, vp9, and h264, and h264 seems to be the best for both FPS and latency. When I try h265, the browser (Chromium 94) refuses to display the stream at all.
- Lowering resolution. If I go from 1080p to 720p, the latency is good, but I don't want to lower resolution.

### What doesn't work
- Lowering appsrc framerate. If I set the appsrc caps and the duration of each appsrc buffer to 30 FPS instead of 60, the latency does not improve significantly.

**Comment by MathieuDuponchelle** [comment]
Interesting, it does sound like your pipeline is hardware-bound. My best guess here is that on your HD graphics machine a software encoder gets picked even for H264 (whereas on your better machine, either nvh264enc gets picked, or your CPU is beefy enough to handle the software encoding in real time).

Have you had a look at CPU usage? If you see at least one core consistently maxed out, that's your problem right there :)

I suppose one thing you could try is take `webrtcsink` entirely out of the equation, and run eg:

```
appsrc name=appsrc ! video/x-raw,format=RGB,framerate=60/1,pixel-aspect-ratio=1/1,width=1920,height=1080 ! videoconvert ! queue ! x264enc ! avdec_h264 ! queue ! autovideosink
```

And verify that this can run real time. You'll want to use the same settings for the encoder that we use in `webrtcsink`.

Note that I'm opened to tweaking those settings if you can find something that does give you the performance boost to get you over the line, but there's only so far you'll be able to go if your hardware is too much of a bottleneck :)

**Comment by MathieuDuponchelle** [comment]
Also note that H264 will definitely be your best choice when it comes to performance, both vp8enc and vp9end are quite greedy. As for H265, support for it is implemented "optimistically", ie I couldn't test against a browser that did support it :)

**Comment by fechan** [comment]
No cores on the CPU get maxed out when I run it, so it's not using a software encoder. I think it's just my hardware then, since it has trouble with the x264enc+avdec_h264 pipeline with the settings webrtcsink uses. I even tried swapping out my appsrc for testvideosrc with testvideosrc with the same caps just to see if it's a problem on the appsrc, and I consistently get `There may be a timestamping problem, or this computer is too slow` from autovideosink.

**Comment by MathieuDuponchelle** [comment]
@fechan looking at the specs from your machine I very much suspect it is a bit underpowered indeed. I'll close this then, thanks for following up :)
