### ISSUE TITLE
Is the default rate for x264enc correct?

### ISSUE THREAD

**Issue by machenmusik** [centricular/webrtcsink#21]
https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L393

Is that really supposed to be `25608u32` ?

**Comment by machenmusik** [comment]
If it actually sends at 25 mbps and receiving devices can't handle it, it might break the receiver...

Since it's still H.264, I assumed it was a typo and should be the same 2048u32 value as https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L401

**Comment by machenmusik** [comment]
> We probably could also expose a "start-bitrate" property to accompany min and max btw

That might be a good idea, to let apps decide to start optimistic or pessimistic.

**Comment by MathieuDuponchelle** [comment]
if I were to guess, I would think it is rather a typo from porting the `2560000` value from the `vp*` case ;)

Anyway, patches welcome :)

**Comment by machenmusik** [comment]
So do we want it at 2048 (so for H264 that is the default starting bitrate regardless of whether or not nvidia) ?  Or 2560 because x264 is worse than Nvidia?  Can make a PR but would like to understand intent to do exactly once ;-)

**Comment by MathieuDuponchelle** [comment]
No specific intent, 2048 is fine :)

**Comment by machenmusik** [comment]
#23
