### ISSUE TITLE
Expose datachannel messages more generally?

### ISSUE THREAD

**Issue by machenmusik** [centricular/webrtcsink#25]
The GstNavigation interface implemented is a bit archaic from the days of DVD navigation menus; as such, other methods of exposing the data channel functionality might be more useful?

For example, data channel messages could be made available as signals, or perhaps something like appsink could receive just those...

Thoughts welcome.

**Comment by MathieuDuponchelle** [comment]
Hey, the idea behind that "default" data channel is for it to only transmit events that can be directly transformed into GStreamer events and forwarded upstream for interpretation / handling. For what it's worth I am going to extend it soon for another project to support sending other types of events (I need seek events), and also to allow specifying the transceiver the event applies to (useful in the case of multiple bundled video streams).

The navigation interface was indeed initially developed for DVD navigation, but it is still the standard mechanism GStreamer elements must implement for user input (eg `wpesrc` implements it).

If you need a custom protocol instead, you can simply add your own data channel (the consumer-added signal will give you access to `webrtcbin` at the right moment), and work from there :)

**Comment by machenmusik** [comment]
@MathieuDuponchelle I tried this, but doing `create-data-channel` in response to `consumer-added` does something bad... after a few seconds, the client seems to re-request either audio or video, which fails and then things are torn down.

**Comment by MathieuDuponchelle** [comment]
@machenmusik not sure what your exact problem is there, but I know that @thiblahute creates his own data channel with no issues with that method at least, so it *should work* if that helps with anything :)

**Comment by machenmusik** [comment]
Thanks - what I discovered is that things seem to be happy if `create-data-channel` happens *before* the pipeline starts playing, but `consumer-added` only occurs *after* the pipeline is playing, and that seems to create a race condition that is easily reproducible with localhost connections.  Moving `consumer-added` to just before pipeline starts playing eliminates the issue even with localhost connections.
