### ISSUE TITLE
No video visible in browser

### ISSUE THREAD

**Issue by zfgrnzfsberire** [centricular/webrtcsink#29]
Hi,

I'm trying to run the demo as described in the README. Unfortunately, the browser hangs on `Status: Sending SDP answer`, and no video is being played. Firefox's `about:webrtc` view indicates that a connection has been established. I can reproduce this on both Firefox and Chromium.

I'm running the following commits (`main` of either repo at the time of this writing):
This repo: `7f000ea42b5f53784775368425b207c05bdad486`
gstreamer: `69863131bdb4ff7f5b51e17f50b0a83522fcc822`

Here's some debug log output (using `GST_DEBUG=4,*webrtc*=7`) of the pipeline I started:
[webrtcsink.log](https://github.com/centricular/webrtcsink/files/8248601/webrtcsink.log)
I inserted a comment in the log at the point where I attempted to start the video in the browser (search for `###` in the log).

Notably, while the video should have been played in the browser, this message was spammed continually:
```log
0:00:14.844600668 188677 0x557f608c5180 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc0> Dropping old item buffer: 0x7f0d6c011ea0, pts 0:00:14.280272108, dts 99:99:99.999999999, dur 0:00:00.023219955, size 2048, offset 629760, offset_end 630784, flags 0x0
0:00:14.853507319 188677 0x557f608c5120 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc1> Dropping old item buffer: 0x7f0d6c011b40, pts 0:00:14.300000000, dts 99:99:99.999999999, dur 0:00:00.033333333, size 614400, offset 429, offset_end 430, flags 0x0
0:00:14.867825925 188677 0x557f608c5180 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc0> Dropping old item buffer: 0x7f0d6c011d80, pts 0:00:14.303492063, dts 99:99:99.999999999, dur 0:00:00.023219955, size 2048, offset 630784, offset_end 631808, flags 0x0
0:00:14.886830703 188677 0x557f608c5120 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc1> Dropping old item buffer: 0x7f0e0c0137e0, pts 0:00:14.333333333, dts 99:99:99.999999999, dur 0:00:00.033333333, size 614400, offset 430, offset_end 431, flags 0x0
0:00:14.891044731 188677 0x557f608c5180 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc0> Dropping old item buffer: 0x7f0d7c004480, pts 0:00:14.326712018, dts 99:99:99.999999999, dur 0:00:00.023219954, size 2048, offset 631808, offset_end 632832, flags 0x0
0:00:14.914218211 188677 0x557f608c5180 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc0> Dropping old item buffer: 0x7f0e0c013240, pts 0:00:14.349931972, dts 99:99:99.999999999, dur 0:00:00.023219955, size 2048, offset 632832, offset_end 633856, flags 0x0
0:00:14.920201347 188677 0x557f608c5120 WARN                  appsrc gstappsrc.c:2597:gst_app_src_push_internal:<appsrc1> Dropping old item buffer: 0x557f608d6c60, pts 0:00:14.366666666, dts 99:99:99.999999999, dur 0:00:00.033333334, size 614400, offset 431, offset_end 432, flags 0x0
```

Please let me know if I can provide additional info to help debug this. The demo video for this plugin looks really cool and I'd really like to run it myself :D

**Comment by MathieuDuponchelle** [comment]
Oops, I've run into this too, I think it's a recent regression but I haven't had time for a proper fix, for now you can comment out https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-plugins-bad/ext/webrtc/gstwebrtcbin.c#L4607-4609 to get unstuck, but please open an issue against GStreamer :)

**Comment by zfgrnzfsberire** [comment]
Wow, that was a quick reply, and you are correct! Commenting out those four lines fixes the issue.

While I don't have the slightest idea what line four thousand six hundred and seven does, I'll open an issue on their Gitlab tomorrow.

Thank you very much for the library and the support! :)

**Comment by MathieuDuponchelle** [comment]
@zfgrnzfsberire don't bother, I am making the fix right now, I'll update you with a link to the MR shortly.

**Comment by MathieuDuponchelle** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1967 :) I'll close this now, thanks for reporting!
