### ISSUE TITLE
Encrypted media stream

### ISSUE THREAD

**Issue by septatrix** [centricular/webrtcsink#46]
It does not seem like this plugin supports TLS encryption. Can this be activated somehow? Alternatively do you consider implementing this features?

**Comment by septatrix** [comment]
On the code I found some references to certificates for the signalling server. Could someone point me to some information on how to use that?

**Comment by MathieuDuponchelle** [comment]
Hey, I think you are conflating two concepts: on the one hand the media streams themselves in webRTC are all mandated to be encrypted with either DTLS (data streams) or SRTP (media streams). On the other hand, the implementation of signalling is left up to the application, our implementation of the signalling server allows for usage of either basic, unencrypted websockets, or secure websockets, that's where the references you found come from. If that's what you are interested in switching on, you should simply consult the `--help` of the executable:

```
 meh   recalculate-latency  …  gstreamer  sandbox  webrtcsink  cargo run -- --help
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/server --help`
webrtcsink-signalling 0.1.0
Mathieu Duponchelle <mathieu@centricular.com>
GStreamer WebRTC sink signalling server

USAGE:
    server [OPTIONS]

OPTIONS:
    -c, --cert <CERT>                      TLS certificate to use
        --cert-password <CERT_PASSWORD>    password to TLS certificate
    -h, --host <HOST>                      Address to listen on [default: 0.0.0.0]
        --help                             Print help information
    -p, --port <PORT>                      Port to listen on [default: 8443]
    -V, --version                          Print version information
 meh   recalculate-latency  …  gstreamer  sandbox  webrtcsink 
 ```

Here is an example invocation, with a certificate I generated using https://github.com/FiloSottile/mkcert:

```
cargo run -- --cert /home/meh/devel/gstreamer/sandbox/mkcert/localhost+1.p12 --cert-password changeit
```

**Comment by septatrix** [comment]
Yes thank you. I did not notice the help option
