### ISSUE TITLE
Panics when trying to use VAAPI plugins

### ISSUE THREAD

**Issue by septatrix** [centricular/webrtcsink#50]
After obtaining the vappi plugins (`GstVaapiEncodeVP8`, `GstVaapiEncodeH264` etc.) the server panics upon an incoming connection.

The last log output from gstreamer before it dies is: `webrtcsink plugins/src/webrtcsink/imp.rs:2598:webrtcsink::webrtcsink::imp:<rswebrtcsink0> applying default configuration on encoder Element { inner: ObjectRef { inner: 0x7f67d40f05a0, type: GstVaapiEncodeVP8 } }`

```
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: webrtcsink::webrtcsink::imp::VideoEncoder::bitrate
             at ./plugins/src/webrtcsink/imp.rs:514:18
   4: webrtcsink::webrtcsink::imp::Consumer::connect_input_stream
             at ./plugins/src/webrtcsink/imp.rs:1130:57
   5: webrtcsink::webrtcsink::imp::WebRTCSink::on_remote_description_set
             at ./plugins/src/webrtcsink/imp.rs:1819:25
   6: webrtcsink::webrtcsink::imp::WebRTCSink::handle_sdp::{{closure}}
             at ./plugins/src/webrtcsink/imp.rs:1981:21
   7: gstreamer::promise::Promise::with_change_func::trampoline
             at /home/septatrix/.cargo/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.6/src/promise.rs:67:13
   8: <unknown>
   9: <unknown>
  10: g_main_context_dispatch
  11: <unknown>
  12: g_main_loop_run
  13: <unknown>
  14: <unknown>
  15: start_thread
  16: __GI___clone3
```

[Log output](https://github.com/centricular/webrtcsink/files/8556956/webrtc.log) from `GST_PLUGIN_PATH=$PWD/target/debug GST_DEBUG="webrtc*:9,vaapi*:9" RUST_BACKTRACE=1 gst-launch-1.0 videotestsrc ! webrtcsink &>webrtc.log`

**Comment by MathieuDuponchelle** [comment]
As you may know, there is no unified interface for encoders in GStreamer. As a consequence, `webrtcsink` needs to be taught about specific elements, if you feel like doing that for the vaapi elements patches are very welcome, I suggest you search for `vp8enc` in `plugins/src/webrtcsink/imp.rs`, and adapt for the vaapi encoder :)

**Comment by septatrix** [comment]
> ...if you feel like doing that for the vaapi elements patches are very welcome, I suggest you search for `vp8enc` in `plugins/src/webrtcsink/imp.rs`, and adapt for the vaapi encoder :)

Thanks, I will definitely take a look and see how easy it is to get this running for VAAPI and/or V4L2. Though I am a bit confused why `webrtcsink` allows dynamic selection of the encoder if it is unable to handle them.

**Comment by MathieuDuponchelle** [comment]
> Though I am a bit confused why webrtcsink allows dynamic selection of the encoder if it is unable to handle them.

So that good souls will contribute patches :P More seriously, it pretty much disallows it by panicking at that stage (with `unreachable!()`), but we should probably also discard those "unknown" encoders at discovery time.

**Comment by septatrix** [comment]
> More seriously, it pretty much disallows it by panicking at that stage (with `unreachable!()`), but we should probably also discard those "unknown" encoders at discovery time.

Or use them in a best-effort manner with reduced integration. It seems like the only panics are when setting the bitrate so how about not changing the bitrate for unknown encoders? This would not be worse than the case when congestion control is disabled.

**Comment by MathieuDuponchelle** [comment]
congestion-control is IMHO a large part of what makes the element useful, the design here is for the element to operate with known elements, just need to teach it about them :)

**Comment by septatrix** [comment]
> ...we should probably also discard those "unknown" encoders at discovery time.

I guess a good place for this would be in [`lookup_codecs`](https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L1283-L1285)? Maybe using `factory.name().as_str()` inside an additional filter comparing it with a hashset?

Also I was wondering about the weird true/false `is_video` tuples (https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L1274-L1278). Is it not possible in `gstreamer-rs` to check if the factory is a child of [`GstVideoEncoder`](https://gstreamer.freedesktop.org/documentation/video/gstvideoencoder.html#GstVideoEncoder)?

**Comment by sdroege** [comment]
Not every video encoder is a subclass of that. You could check the element factory's [classification](https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/0.18/docs/gstreamer/struct.ElementFactory.html#method.klass) though. `klass.split('/')` should contain `Video` and `Encoder`.

**Comment by septatrix** [comment]
> Not every video encoder is a subclass of that.

Do you have an example of one? The ones currently implemented are and I was unable to find one which is not a subclass after 5 minutes in the documentation.

> You could check the element factory's [classification](https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/0.18/docs/gstreamer/struct.ElementFactory.html#method.klass) though. `klass.split('/')` should contain `Video` and `Encoder`.

I also found [`ElementFactoryType::VIDEO_ENCODER`](https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/0.18/docs/gstreamer/struct.ElementFactoryType.html#associatedconstant.VIDEO_ENCODER). Does that serve the same purpose? If so then that seems a bit more robust than the classification (and presumably insignificantly faster).

**Comment by sdroege** [comment]
It's doing exactly the same in the same way, yes.

**Comment by MathieuDuponchelle** [comment]
> I guess a good place for this would be in [lookup_codecs](https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L1283-L1285)? Maybe using factory.name().as_str() inside an additional filter comparing it with a hashset?

Yes, that's pretty much what I would have in mind.

> Also I was wondering about the weird true/false is_video tuples (https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L1274-L1278). Is it not possible in gstreamer-rs to check if the factory is a child of [GstVideoEncoder](https://gstreamer.freedesktop.org/documentation/video/gstvideoencoder.html#GstVideoEncoder)?

I suppose you could do it that way yes, but we already have the information and its mapping to a tuple seems straightforward enough to me :)

**Comment by septatrix** [comment]
> > I guess a good place for this would be in [lookup_codecs](https://github.com/centricular/webrtcsink/blob/main/plugins/src/webrtcsink/imp.rs#L1283-L1285)? Maybe using factory.name().as_str() inside an additional filter comparing it with a hashset?
> 
> Yes, that's pretty much what I would have in mind.

Alright. I might give it a shot then.

> I suppose you could do it that way yes, but we already have the information and its mapping to a tuple seems straightforward enough to me :)

It provides a second source of truth which might get out of sync etc whereas a simple `impl ... is_video(&self) -> bool { self.has_type(ElementFactoryType::VIDEO_ENCODER) }` would do the same without any manual bookkeeping ;)

**Comment by MathieuDuponchelle** [comment]
> It provides a second source of truth which might get out of sync etc whereas a simple impl ... is_video(&self) -> bool { self.has_type(ElementFactoryType::VIDEO_ENCODER) } would do the same without any manual bookkeeping ;)

Ah, you're actually concerned about the field right? Yeah that could arguably make things cleaner, but as Sebastian said you'd want to check the factory classification rather than the inheritance tree :)

**Comment by septatrix** [comment]
> Ah, you're actually concerned about the field right? Yeah that could arguably make things cleaner, but as Sebastian said you'd want to check the factory classification rather than the inheritance tree :)

Yeah, and the tuple mapping is a symptom of having that manual bookkeeping in the struct. If you want I could make a PR for that

**Comment by MathieuDuponchelle** [comment]
sure

**Comment by septatrix** [comment]
You can also expect a PR for `v4l2h264enc` once I got my hands on a RPi ;)
