### ISSUE TITLE
Plans for an h264-capable pad?

### ISSUE THREAD

**Issue by joaoantoniocardoso** [centricular/webrtcsink#59]
Hi,

I am using an _h264_ encoded camera and I noticed that the _webrtcsink_ only accepts _video/x-raw_ capability. To use it with my video pipeline, it has to be decoded to _raw_, then passed to webrtcsink (which itself is encoding back to h264? - I'm not sure how, but my browser say it is using the h264 decoder), and my application hardware has some constraints for doing that.

Is it possible to add _video/x-h264_ or _application/x-rtp_ capability? If so, are there any plans for implementing that?

Thank you!

**Comment by MathieuDuponchelle** [comment]
Hey, a large part of webrtcsink's value is its ability to perform congestion control, and also to serve the same stream to multiple consumers. For the former, the ability for webrtcsink to adapt the bitrate of the video stream it sends out is mandatory, and for the latter the ability for webrtcsink to request keyframes is very nice to have.

Now, being aware of these limitations (no congestion control possible, degraded consumer experience), if someone still feels like proposing a patch that implements what you're looking for, without making the current code overly complex, I wouldn't be opposed to merging it; but I currently don't have a plan to implement this myself :)

**Comment by MathieuDuponchelle** [comment]
Closing in favor of https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/258
