### ISSUE TITLE
Releases via tags

### ISSUE THREAD

**Issue by patrickelectric** [centricular/webrtcsink#61]
It would be nice to have tags to track specific gstreamer versions.
E.g: 55d30db53bb3931f6477b6c1bad4de2a5ec5f7e4 works with 1.19
So a 1.19 tag would be nice to have

**Comment by MathieuDuponchelle** [comment]
Hey, how is latest main broken with 1.19 ooc?

**Comment by MathieuDuponchelle** [comment]
ping @patrickelectric
