### ISSUE TITLE
SDP Peer candidates do not include VPN addresses (or WAN address from what I can tell)

### ISSUE THREAD

**Issue by colemickens** [centricular/webrtcsink#69]
Thanks for the help on the last issue, adding `libnice` to my environment has gotten me much closer.

It looks like I'm failing STUN/ICE right now. When I look in Firefox, the only peer candidates that it seems to get are the broadcaster's private IPv4 and some IPv6 addresses. I don't see my Tailscale ips offered as candidates, nor do I see anything that looks like my networks' WAN addresses offered as a candidate.

Since I'm accessing the html through the tailscale IP, and the private IPv4 is not accessible, it seems understandable that the SDP exchange process does not finish.

However, how can I control this or influence it? Particularly I'm assuming there must be code somewhere that filters the candidates... that is maybe overly aggressive? Or maybe I need an option to say "please discover my WAN address as a candidate?"?

Thanks!

**Comment by colemickens** [comment]
Actually, I take that back, it looks like my WAN ip starts with 198 so I missed it for a second.

So in Firefox, one candidate is:


```
Received {"type":"peer","peerId":"d071bdeb-03d5-432d-a1ed-0fed6792fee8","ice":{"candidate":"candidate:22 1 UDP 1763705599 198.244.104.13 34780 typ srflx raddr 192.168.54.101 rport 34780","sdpMLineIndex":0}}
```

But ultimately I'm still mostly stuck with "Sending SDP Answer" in firefox.

**Comment by colemickens** [comment]
Actually, I do even see the tailscale vpn ip as a candidate:

```
Received {"type":"peer","peerId":"29fc3747-98a7-4118-9e97-59cf5cd3bb83","ice":{"candidate":"candidate:6 1 TCP 1010827775 100.112.137.125 50345 typ host tcptype passive","sdpMLineIndex":0}}
```

incidentally right before the  console message "Sending SDP Response", but it doesn't seem like it logs the  candidate it picks, or why it might've failed.

**Comment by colemickens** [comment]
It seems like this could possibly be related? https://github.com/centricular/gstwebrtc-demos/issues/160

**Comment by MathieuDuponchelle** [comment]
Hey, I've never tried to use `webrtcbin` with a VPN involved to be honest.

I don't think this is a `webrtcsink` issue though, if you can provide more information (eg `G_MESSAGES_DEBUG=all NICE_DEBUG=all,libnice-nice-verbose`) you might want to report this against libnice :)

Closing.
