### ISSUE TITLE
Shared encoding between consumers

### ISSUE THREAD

**Issue by massis08** [centricular/webrtcsink#70]
Hello,

I am trying to optimize the webrtcsink plugin so that the same consumers on different browser tabs share the same encoding. 
The idea is to have the encoding elements linked to a tee and a fakesink, and to the tee we link the differents webrtcbin. 
I don't know if this is the right approach for the way webrtcsink is implemented. So, if you could give me some guidelines on this matter, it would be really appreciated!

Besides this, me and my colleague @leaonidas added support for memory NVMM in a fork, I don't know if this kind of work is on the roadmap but if you want to take a look: [massis@fork](https://github.com/centricular/webrtcsink/compare/main...massis08:webrtcsink:20220621-memory-nvmm-h264-vp8)

**Comment by MathieuDuponchelle** [comment]
Closing in favor of #59 , this is a request I have had a few times. As long as you understand there are limitations to the approach (which I listed there), I am not opposed to the feature. I had one potential candidate willing to sponsor this but no news recently, and I know that @thiblahute might have plans to work on this soonish.

Regarding NVMM, please make a PR, that looks useful :)
