### ISSUE TITLE
Front end crashes on firefox 

### ISSUE THREAD

**Issue by mikolajkniejski** [centricular/webrtcsink#71]
## Summary
When trying to start a stream, the firefox tab crashes as soon as the webrtc connection is meant to start.
## Steps to reproduce
Follow the steps in README using a Firefox browser.
## What is the current bug behavior?
Tab crashes.
## What is the expected correct behavior?
Tab doesn't crash and the stream starts.
## Relevant logs and/or screenshots
```
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:8 1 TCP 1015022335 fe80::bcbf:795c:4b9b:6407 9 typ host tcptype active","sdpMLineIndex":0}} 
Got local description: {"type":"answer","sdp":"v=0\r\no=mozilla...THIS_IS_SDPARTA-99.0 4747432338464604538 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 26:27:F3:F9:AD:A0:2F:F6:30:A4:E6:CE:FC:E6:FD:97:2A:A2:8C:69:4A:ED:D3:EB:81:1D:C2:73:40:4B:10:99\r\na=group:BUNDLE video0\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 100\r\nc=IN IP4 0.0.0.0\r\na=recvonly\r\na=extmap:1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=fmtp:96 max-fs=12288;max-fr=60\r\na=fmtp:100 apt=96\r\na=ice-pwd:2abe31c81f00aedb0e51e9890ee93d37\r\na=ice-ufrag:7a0da430\r\na=mid:video0\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP9/90000\r\na=rtpmap:100 rtx/90000\r\na=setup:active\r\na=ssrc:2137346384 cname:{4a269b7f-996e-461a-9071-a715fba29cc0}\r\n"} 
Object { peer_connection: RTCPeerConnection, ws_conn: WebSocket, peer_id: "8fa07323-a92e-4079-9a9b-c2ab2bf18119", our_id: "1854c30a-e939-408c-9efc-9690f777a30c", closed_callback: session_closed(peer_id), data_channel: null, input: null, getVideoElement: getVideoElement(), resetState: resetState(), handleIncomingError: handleIncomingError(error), … }
Sending SDP answer
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:13 1 UDP 1679819007 213.5.4.15 37090 typ srflx raddr 192.168.0.101 rport 37090","sdpMLineIndex":0}}
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:14 1 TCP 847249663 213.5.4.15 9 typ srflx raddr 192.168.0.101 rport 9 tcptype active","sdpMLineIndex":0}}
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:15 1 TCP 843055359 213.5.4.15 47091 typ srflx raddr 192.168.0.101 rport 47091 tcptype passive","sdpMLineIndex":0}}
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:16 1 UDP 1679819263 213.5.4.15 37097 typ srflx raddr 172.30.0.1 rport 37097","sdpMLineIndex":0}} 
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:17 1 TCP 847249919 213.5.4.15 9 typ srflx raddr 172.30.0.1 rport 9 tcptype active","sdpMLineIndex":0}} 
Received {"type":"peer","peerId":"8fa07323-a92e-4079-9a9b-c2ab2bf18119","ice":{"candidate":"candidate:18 1 TCP 843055615 213.5.4.15 55879 typ srflx raddr 172.30.0.1 rport 55879 tcptype passive","sdpMLineIndex":0}}
```

[out.webm](https://user-images.githubusercontent.com/64133041/179389561-80b318cc-31d3-4dc0-98c1-23048e91c976.webm)

## Desktop
OS: Linux x86_64

Browser: Firefox

This has been reproduced on more than one machine tho.

**Comment by MathieuDuponchelle** [comment]
What do you mean by crash? This isn't a very useful report ;)

**Comment by mikolajkniejski** [comment]
@MathieuDuponchelle Updated the bug report

**Comment by mikolajkniejski** [comment]
@MathieuDuponchelle Hi, have you looked at this issue?

**Comment by compiaffe** [comment]
@mikolajkniejski Which firefox version you are running?

**Comment by MathieuDuponchelle** [comment]
Hey @mikolajkniejski I hadn't noticed you had updated the issue sorry. As @compiaffe asked, what firefox version? Does that happen with chrome? I'm not quite sure how one goes about debugging firefox crashes to be honest :)

**Comment by mikolajkniejski** [comment]
103.0 (64-bit) for ubuntu canonical. It doesn't happen with chrome

**Comment by MathieuDuponchelle** [comment]
OK. I just gave a spin with latest webrtcsink, latest gst, and firefox 102.0 (fedora 35), I cannot reproduce. That is concerning, but I'm not a Firefox developer and I don't really know what to ask from you to debug a browser-side crash :( Can you perhaps try with firefox 102? 103 isn't yet available in fedora updates.

**Comment by MathieuDuponchelle** [comment]
Ah, interesting, I see that you can go to `about:crashes`, then you might see a report that you can submit, once submitted you can click view and see a bunch of information, including dumps.

**Comment by mikolajkniejski** [comment]
https://crash-stats.mozilla.org/report/index/2d62ee67-aa99-4d89-8dcc-852490220808#tab-details

**Comment by mikolajkniejski** [comment]
I tried on Firefox 101 and the issue is still there

**Comment by MathieuDuponchelle** [comment]
I see thanks. Obviously that is first a firefox problem, and you should report this crash to them ASAP, but we can still try to identify what is so special about our video frames that it throws it off that badly, perhaps webrtcsink uses a colorspace it doesn't like on your end?

You'll want to set `GST_DEBUG_DUMP_DOT_DIR` and observe the consumer dumps now I think.

**Comment by MathieuDuponchelle** [comment]
ping @mikolajkniejski

**Comment by compiaffe** [comment]
@MathieuDuponchelle Miklolaj is on holiday until the beginning of next week.

**Comment by compiaffe** [comment]
FYI @noverby

**Comment by mikolajkniejski** [comment]
It started working for me

**Comment by noverby** [comment]
@mikolajkniejski With what version of Firefox?

**Comment by mikolajkniejski** [comment]
103.0, the same one

**Comment by MathieuDuponchelle** [comment]
For what it's worth I wouldn't recommend popOS either, in any case yay for downstream patches introducing bugs :(
