### ISSUE TITLE
nice.c:298:on_resolve_host: failed to resolve Error resolving “{GUID}.local”: Name or service not known

### ISSUE THREAD

**Issue by colemickens** [centricular/webrtcsink#83]
After rebasing on all latest changes, I'm seeing this behavior in a scenario that seemed to work previously.

This is me starting a producer and then trying to connect from Firefox. It happens that Firefox is running on a local network peer to the producer, and is accessing it over its LAN ip.

```
0:00:16.634204449 1163288      0x1e35070 ERROR             webrtcnice nice.c:298:on_resolve_host: failed to resolve: Error resolving “3cda1f2e-8887-4e72-87b1-f682ce4d4832.local”: Name or service not known
0:00:16.673476547 1163288      0x1e35070 ERROR             webrtcnice nice.c:298:on_resolve_host: failed to resolve: Error resolving “3cda1f2e-8887-4e72-87b1-f682ce4d4832.local”: Name or service not known
0:00:23.838021949 1163288      0x229daa0 ERROR                    gcc plugins/src/gcc/imp.rs:1100:webrtcsink::gcc::imp:<rtpgccbwe1> pause task, reason: Flushing
```

This is with gstreamer-42838c3b9efb1c726f6cba4e25ecf8d47f88c827 as my base, and then e0ad7e4c1686d5e5ea7880779ffb2339d5ecfb24 with a couple small js touchups on top just for pointing to the right `ws_url`.

**Comment by colemickens** [comment]
Disabling `media.peerconnection.ice.obfuscate_host_addresses` in firefox gets me around this temporarily. I guess Firefox is advertising some mdns address. Not sure where it's getting that from. Also, I might not have avahi running next to the webrtcsink producer.

**Comment by MathieuDuponchelle** [comment]
Hey @colemickens , to be clear is this causing negotiation to fail, or are you just annoyed by the error logging? In any case, sorry for being a bit strict about this but this is most likely not something I can address at the webrtcsink level, instead you will want to either file an issue against libnice, or perhaps [find one](https://gitlab.freedesktop.org/libnice/libnice/-/issues/?search=local&sort=created_date&state=all&first_page_size=20) already filed.

Closing, but please re-open if it turns out webrtcsink is the culprit after all.

**Comment by colemickens** [comment]
It's causing negotiation to fail. From what I could see, Firefox sends the mdns endpoints in lieu of any local ip candidates (as a privacy mechanism). Since the producer can't resolve it (and for some reason webrtc from two local clients through my WAN never connects), it does just fail.

But I think your assessment is also probably right, that this isn't really a webrtcsink issue to address. Thanks for triaging.

**Comment by MathieuDuponchelle** [comment]
Don't hesitate to update this issue once you get resolution (hah)
