### ISSUE TITLE
readme: add gst-launch with meta example

### ISSUE THREAD

**Issue by colemickens** [centricular/webrtcsink#84]
please, and thank you. I'm new to gstreamer and can't really figure out how meta works with gst-launch, nor has Google turned up anything helpful yet.

**Comment by colemickens** [comment]
` meta="a-structure, display-name=${dname}" ` is what I came up with, is that the simplest way?

**Comment by joaoantoniocardoso** [comment]
So, an example would be helpful indeed. Yesterday I was updating my application to work with the meta instead of display-name, and it follows the gst Structure syntax. To construct it in Rust you can do as follows:

```rust
let metadata = gstreamer::Structure::new("meta", &[(&"display-name", &"potato")]).to_string();

let pipeline_string = " ! webrtcsink stun-server={stun_endpoint} \
      turn-server={turn_endpoint} \
      signaller::address={signalling_endpoint} \
      video-caps={capability} \
      meta={metadata:?}

```

Hope it helps!

**Comment by joaoantoniocardoso** [comment]
Since it is a metadata, I wonder how to serialize a `gstreamer::Structure` from a Rust `Struct`, it would be very helpful.

**Comment by MathieuDuponchelle** [comment]
thanks @joaoantoniocardoso :) @thiblahute care to comment on this?

**Comment by thiblahute** [comment]
> meta="a-structure, display-name=${dname}" is what I came up with, is that the simplest way?

Yes this is the right way to do it.

> So, an example would be helpful indeed. Yesterday I was updating my application to work with the meta instead of display name, and it follows the [Gst Structure syntax](https://gstreamer.freedesktop.org/documentation/gstreamer/gststructure.html?gi-language=c#gststructure-page). To construct it in Rust you can do as follows:
> ``` rust
> let metadata = gstreamer::Structure::new("meta", 
>    &[
>       (&"display-name", &"potato")
>   ]
> ).to_string();
> let pipeline_string = format!(
>    " ! webrtcsink stun-server={stun_endpoint} \
>      turn-server={turn_endpoint} \
>      signaller::address={signalling_endpoint} \
>      video-caps={capability} \
>      meta={metadata:?}"
> );
> ```

This is correct but I would find it cleaner to use `metadata.to_string()` (instead of abusing the Debug implementation ) or  retrieve the element and set the structure as a prop fwiw :-)

> Since it is a metadata, I wonder how to serialize a gstreamer::Structure from a Rust struct, it would be very helpful.

We should implement that with Serde at some point I think, but it is not done. I implemented a [`json_to_gst_structure`](https://github.com/thiblahute/webrtcsink/blob/webrtcsrc/plugins/src/utils.rs#L78) function in my `webrtcsrc` branch which is fairly simple if it can help meanwhile.

**Comment by thiblahute** [comment]
@colemickens btw PR is welcome to add the example in the readme as suggested here :-)

**Comment by joaoantoniocardoso** [comment]
> This is correct but I would find it cleaner to use `metadata.to_string()` (instead of abusing the Debug implementation ) or retrieve the element and set the structure as a prop fwiw :-)

`metadata` is already a String  (you might just misread it?), and the debug `:?` is just there to get `\"` around the (String) metadata, as `meta=\"{metadata}\"`.

> We should implement that with Serde at some point I think, but it is not done. I implemented a [`json_to_gst_structure`](https://github.com/thiblahute/webrtcsink/blob/webrtcsrc/plugins/src/utils.rs#L78) function in my `webrtcsrc` branch which is fairly simple if it can help meanwhile.

Nice! That's very helpful, thanks!

**Comment by MathieuDuponchelle** [comment]
Closing, @colemickens if you decide to update the README it now lives at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs :)
