### ISSUE TITLE
Server doesn't fully end a broken connection

### ISSUE THREAD

**Issue by charodziej** [centricular/webrtcsink#92]
If the client is unexpectedly disconnected from the signalling server, the session on the server will remain open until the stream is finished.
This can be especially problematic on low-powered devices, which could have significant performance issues when wasting processing power and memory.

Steps to reproduce:

1. Run the demo
2. Add many (roughly 10 to 20 streams) to see a noticeable difference in processor usage
3. Close the browser window or refresh the page
4. Even after a long time, gst-launch will keep using resources
5. When the stream ends, many end_session function calls from webrtcsink_signalling::handlers can be seen in the debug terminal

My guess would be that the session isn't correctly ended in this case, however I do not have any Rust experience, so it's hard to pinpoint the exact source of the issue.

**Comment by MathieuDuponchelle** [comment]
This sounds surprising, websocket connections should usually time out (typically 30 seconds). I suppose we could sophisticate the javascript example to close the connection / end sessions manually on tab closure, but that's not "unexpected disconnection" either. Maybe double check your test with a longer input stream to verify that sessions do get ended eventually?

**Comment by charodziej** [comment]
Thanks for the quick response!
I've just run another test, where I've broken the network connection and then left the server running.
Unfortunately, the processor (and memory) usage remained the same after 10mins after the disconnection. This should have been more than enough for all the connections to timeout, but the server has not logged anything about connections being ended. 

Interestingly enough, in a separate test, when I closed the browser window instead of killing the connection, websocket connections were closed immediately and the remove_peer was shown in the logs of the signalling server, but the problem with cpu usage remained exactly the same.

If there's any more information I could provide, I will be very happy to deliver.

**Comment by MathieuDuponchelle** [comment]
OK. Are you running latest main ooc?

**Comment by MathieuDuponchelle** [comment]
Resetting to 2dc42ba0db1efee376ace7d8d7a7adecede47a0a fixes it on my end, regression from https://github.com/centricular/webrtcsink/pull/76 I'm afraid, cc @thiblahute :)

**Comment by MathieuDuponchelle** [comment]
Looks like `remove_peer` in `signalling/src/handlers/mod.rs` no longer ends sessions when a consumer is removed, that's broken. Also I hadn't noticed, but all those iterations of the complete list of peers to notify listeners aren't great :(

**Comment by MathieuDuponchelle** [comment]
same with iterating all sessions  everytime we need to find which one a peer is a producer in

**Comment by charodziej** [comment]
Thank you for the fix!
I've just tested it in my environment and everything works as it should.

**Comment by MathieuDuponchelle** [comment]
Great, thanks again for the report :)

**Comment by anhquan1012** [comment]
Hello @MathieuDuponchelle 
I met the same problem like the author and I run with your fix but the memory does not get fully deallocated when I close the browser. I think there is still some memory leak in the code.
Can you take a look at to see if this is a problem?

**Comment by MathieuDuponchelle** [comment]
@anhquan1012 What version are you running exactly? Have you checked the logs to see if the sessions were getting closed?

**Comment by anhquan1012** [comment]
I am using fix-consumer-disconnection branch without **drop(state)** in ./plugins/src/gcc/imp.rs (because it caused the error below):
```
5:49:26.000277746 11966 0x7fee32c9eb60 ERROR                    gcc plugins/src/gcc/imp.rs:1100:webrtcsink::gcc::imp:<rtpgccbwe215> pause task, reason: Flushing
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to pause pad task", filename: "/root/.cargo/git/checkouts/gstreamer-rs-79e52a2d27eb91a3/e229288/gstreamer/src/auto/pad.rs", function: "gstreamer::auto::pad", line: 491 }', plugins/src/gcc/imp.rs:1057:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
I checked the logs in end_session (line 686 in ./plugins/src/webrtcsink/imp.rs) and saw that the sessions were closed (the cpu was fully free).

**Comment by MathieuDuponchelle** [comment]
@anhquan1012 why are you using a branch when it has been merged? Please try with main :) I think I'm going to have to start deleting branches so people don't do that :man_facepalming:
