### ISSUE TITLE
Passing arguments to signalling server to change port. Aquiring peer_id.

### ISSUE THREAD

**Issue by wujekbrezniew** [centricular/webrtcsink#95]
Hi,

Is it posible to pass arguments to "cargo run --bin server" to set different port than "8443"?
Does signalling server provide any way to obtain peer_id?

**Comment by MathieuDuponchelle** [comment]
`cargo run --bin server -- --help` says yes to your first question.

Please reword your second question, I don't understand it :)

**Comment by wujekbrezniew** [comment]
Thanks for your reply.
As far as i understand signalling server is responsible for generating peer id of specific connection. Can i somehow get this id from signalling server? I want to assign specific stream to specific video element on frontend with additional websocket connection to backend that i written in Node fort managing signalling server and gstreamer pipelines.

**Comment by MathieuDuponchelle** [comment]
The very first message from the signalling server to any peer that connects is a welcome message that contains the peer_id: https://github.com/centricular/webrtcsink/blob/main/protocol/src/lib.rs#L18 . Note that when a peer sets its own status, it can also provide arbitrary metadata that will be communicated to any Listening peer: https://github.com/centricular/webrtcsink/blob/main/protocol/src/lib.rs#L54 . You could also use that to advertise your own identifiers if that's useful to you.

I will close this now, I try to keep the issue tracker tidy by aggressively closing issues that don't have action items :)
