### ISSUE TITLE
Do you know the cause of the error below?

### ISSUE THREAD

**Issue by s-muramoto** [centricular/webrtcsink#96]
Do you know the cause of the error below?

Execution environment　: AWS EC2  ubuntu22.04
browse : Google Chrome or  Firefox or Edge

When you access it with a browser, you can see the test data for a moment, but it disappears immediately and an error occurs.

$ gst-launch-1.0 webrtcsink name=ws videotestsrc ! ws.
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
[OpenH264] this = 0x0x7f94fc013f80, Error:CWelsH264SVCEncoder::EncodeFrame(), cmInitParaError.
thread '<unnamed>' panicked at 'not implemented: Factory openh264enc is currently not supported', plugins/src/webrtcsink/imp.rs:581:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0:00:02.548243999 23009 0x7f950800c380 ERROR             webrtcsink plugins/src/webrtcsink/imp.rs:1624:webrtcsink::webrtcsink::imp: session e0ded6ff-4b8c-4d16-ab87-240d681f9159 error: GStreamer encountered a general supporting library error., details: Some("/home/gst-user/.cargo/git/checkouts/gstreamer-rs-79e52a2d27eb91a3/e229288/gstreamer/src/subclass/element.rs(369): gstreamer::subclass::element (): /GstPipeline:session-pipeline-e0ded6ff-4b8c-4d16-ab87-240d681f9159/GstWebRTCBin:webrtcbin-e0ded6ff-4b8c-4d16-ab87-240d681f9159/GstRtpBin:rtpbin/GstBin:bin2/GstRTPGCCBwE:rtpgccbwe0:\nPanicked: not implemented: Factory openh264enc is currently not supported")
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', plugins/src/webrtcsink/imp.rs:1718:43
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', plugins/src/webrtcsink/imp.rs:1758:64
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by MathieuDuponchelle** [comment]
The message of the error seems clear enough :) If you want webrctsink to use `openh264enc` you need to add support for it, grep for `x264enc` in the source code for instance. Feel free to submit a patch for review once you have something working!
