### ISSUE TITLE
Using webrtcsink with python bindings

### ISSUE THREAD

**Issue by mattfeury** [centricular/webrtcsink#98]
Hello all,

Big fan of this plugin and the approach it's taken. I've managed to get everything built and working from a gstreamer cli perspective (as detailed in the readme).

I'm now attempting to use it in an application that has been using pygobject3 to wrap the Gstreamer work. This has been working well before the introduction of webrtcsink. However, it's been using the publicly available gstreamer binaries (via apt install). Since webrtcsink requires a gstreamer build from source, I've changed our application to leverage that. However, it seems as if there are some [known](https://stackoverflow.com/questions/20975411/why-does-my-self-built-pygobject-segfault-on-importing-gtk-or-gdk) [issues](https://stackoverflow.com/questions/67416380/getting-segmentation-fault-in-import-gi-repository-in-python-pygobject) around using python bindings with a custom built gstreamer build. Now, when I attempt to run the application (do just a basic import), I get a segfault. 

I realized this may not be exactly an issue with webrtcsink, but seeing as how a build from source is a requirement for running the plugin and gstreamer itself doesn't recommend using the CLI for production purposes, i'm  interested in the community's take on the best way to get things running here. has anyone been able to run this using python bindings? if not, how are folks "productionizing" this plugin?

**Comment by MathieuDuponchelle** [comment]
Have you tried running the application inside gstreamer's devenv? On my end everything seems to be working nominally (Fedora 36, close to latest gst main):

```
meh   qtmux-no-timescale-precision-loss  ~  devel  gstreamer  ninja -C build devenv
ninja: Entering directory `build'
[0/1] Running external command devenv (wrapped by meson to set env)
 meh   qtmux-no-timescale-precision-loss  ~  devel  gstreamer  python3 -c "from gi.repository import Gst"
<string>:1: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
 meh   qtmux-no-timescale-precision-loss  ~  devel  gstreamer  
 ```

**Comment by mattfeury** [comment]
i've been using a cerbero based build actually based on the gstreamer recommendation (since i won't be doing any custom gstreamer development myself but just embedding the build in our application/dockerfile). i can give the meson build approach a shot though

**Comment by MathieuDuponchelle** [comment]
@mattfeury ah I see, probably worth collecting a stacktrace and reporting against GStreamer's gitlab

**Comment by MathieuDuponchelle** [comment]
Cool thanks :) Closing here
